<a href="https://colab.research.google.com/github/mozaid01/my-first-project/blob/main/Module2_Activity2_1_NumPy_Lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Course: Data Analytics Using Python (AIL0202)
## Module 2 – Activity 2.1
### NumPy Hands-on Lab (5 Marks)


### Instructions:
- Complete all tasks.
- Run each cell and show outputs.
- Add comments wherever required.
- Submit the completed notebook(PDF) on LMS.

Name: Mohd zaid

Roll No.: betn1ai25088


In [ ]:
# Import NumPy
import numpy as np
print('NumPy Version:', np.__version__)


## Task 1: Array Creation(1 Mark)

Create:

1D array of 10 integers

2D array (3×3 matrix)

Identity matrix of size 4

Random array (5×5)

In [6]:
# Create required arrays here

# 1D array of 10 integers
import numpy as np
a = np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

# 3x3 matrix
import numpy as np
a = np.array([[3,5,7],[2,4,6],[7,8,9]])
print(a)

# Identity matrix of size 4
import numpy as np
a = np.eye(4)
print(a)

# Random 5x5 matrix
import numpy as np
a = np.random.rand(5,5)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]
[[3 5 7]
 [2 4 6]
 [7 8 9]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0.72421388 0.02133666 0.94844375 0.25125361 0.2962501 ]
 [0.65438184 0.40607871 0.05294321 0.40288655 0.60334685]
 [0.76826493 0.84951183 0.43502485 0.550841   0.56773131]
 [0.99430651 0.42171427 0.83997253 0.3291144  0.54770795]
 [0.49256888 0.68654554 0.22237107 0.51161728 0.00354114]]


## Task 2: Indexing & Slicing (1 Mark)

Given:

A = np.arange(1, 26).reshape(5,5)

Perform:

Extract 2nd row

Extract 3rd column

Extract 2×2 submatrix (center)

Reverse last row

In [26]:
A = np.arange(1, 26).reshape(5,5)
print(A)

# Extract 2nd row
import numpy as np
a = np.arange(1,26)
a = a.reshape(5,5)
print('print the matrix')
print(a)
print('2nd row')
second_row = A[1]
print(second_row)

# Extract 3rd column
print('3rd column')
third_column = A[:,2]
print(third_column)
print(type(third_column))
# Extract 2x2 center matrix
centre = A[1:3,1:3]
print('center matrix')
print(centre)

# Reverse last row
reversed = A[4,::-1]
print('reverse last row')
print(reversed)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
print the matrix
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
2nd row
[ 6  7  8  9 10]
3rd column
[ 3  8 13 18 23]
<class 'numpy.ndarray'>
center matrix
[[ 7  8]
 [12 13]]
reverse last row
[25 24 23 22 21]


## Task 3: Broadcasting(1 Mark)

Perform broadcasting operations on matrix A created in Task-2.

Add scalar 10 to matrix A

Add vector [1,2,3,4,5] to each row

Normalize matrix values between 0–1

In [34]:
# Perform broadcasting operations here
import numpy as np
A = np.arange(1, 26).reshape(5,5)
print(A)

# Add scalar 10 to matrix
add = A + 10
print('adding scaler 10')
print(add)

# Add vector [1,2,3,4,5] to each row
add_vector = A + [1,2,3,4,5]
print('adding vector')
print(add_vector)
# Normalize matrix between 0 and 1
min_value = np.min(A)
max_value = np.max(A)
print('min value')
print(min_value)
print('max value')
print(max_value)


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
adding scaler 10
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]
adding vector
[[ 2  4  6  8 10]
 [ 7  9 11 13 15]
 [12 14 16 18 20]
 [17 19 21 23 25]
 [22 24 26 28 30]]
min value
1
max value
25


## Task 4: Vectorized Computation(1 Marks)

Perform element-wise multiplication
Compute dot product
Compute mean, standard deviation

In [44]:
X = np.array([1,2,3,4])
Y = np.array([5,6,7,8])

# Element-wise multiplication
import numpy as np
X = np.array([1,2,3,4])
Y = np.array([5,6,7,8])
multi = X * Y
print('Element multiplication')
print(multi)

# Dot product
dot = np.dot(X,Y)
print('Dot product')
print(dot)
# Mean and Standard Deviation
mean_x = np.mean(X)
print('mean of x')
print(mean_x)
mean_y = np.mean(Y)
print('mean of y')
print(mean_y)
print(f"standard deviation:{sd:.2f}")

Element multiplication
[ 5 12 21 32]
Dot product
70
mean of x
2.5
mean of y
6.5


NameError: name 'sd' is not defined

Task 5: Mini Case Problem (1 Mark)

Dataset: Student marks (5 students, 3 subjects)

Compute total and average per student

Find topper

Find subject-wise highest score

In [47]:
marks = np.array([[80,75,90],[60,88,70],[95,92,85],[70,65,60],[88,78,84]])
# Compute totals, averages, topper
total = np.sum(marks, axis=1)
average = np.mean(marks, axis=1)
topper = np.max(total)
print('total marks')
print(total)
print('average marks')
print(average)
print('topper')
print(topper)

total marks
[245 218 272 195 250]
average marks
[81.66666667 72.66666667 90.66666667 65.         83.33333333]
topper
272
